name: Generate Snake Game

on:
  schedule:
    - cron: "0 0 * * *"  # Runs once a day at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Generate Snake game from contribution grid
        uses: Platane/snk@v3
        with:
          github_user_name: YeetTheAnson
          outputs: dist/github-contribution-grid-snake.svg

      - name: Commit and push the Snake game
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Generate Snake game"
          git push
